# SPDX-FileCopyrightText: 2024 Tiz
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure endlessh path exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: 0700
    owner: "{{ endlessh_uid }}"
    group: "{{ endlessh_gid }}"
  with_items:
    - {path: "{{ endlessh_base_path }}", when: true}

- name: Ensure Endlessh support files created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ endlessh_base_path }}/{{ item }}"
    owner: "{{ endlessh_uid }}"
    group: "{{ endlessh_gid }}"
    mode: 0640
  with_items:
    - labels

- name: Ensure endlessh network is created in Docker
  community.docker.docker_network:
    name: "{{ endlessh_container_network }}"
    driver: bridge

- name: Ensure endlessh container image is pulled
  community.docker.docker_image:
    name: "{{ endlessh_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure endlessh.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/endlessh.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ endlessh_identifier }}.service"
    mode: 0644
