# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Tiz
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Endlessh path exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ endlessh_uid }}"
    group: "{{ endlessh_gid }}"
  with_items:
    - "{{ endlessh_base_path }}"

- name: Ensure Endlessh support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ endlessh_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ endlessh_uid }}"
    group: "{{ endlessh_gid }}"
  with_items:
    - labels

- name: Ensure Endlessh container image is pulled
  community.docker.docker_image:
    name: "{{ endlessh_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ endlessh_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else endlessh_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure Endlessh container network is created
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ endlessh_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure Endlessh systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/endlessh.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ endlessh_identifier }}.service"
    mode: "0644"
