# SPDX-FileCopyrightText: 2024 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Tiz
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of Endlessh systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ endlessh_identifier }}.service"
  register: endlessh_service_stat

- when: endlessh_service_stat.stat.exists | bool
  block:
    - name: Ensure Endlessh systemd service is stopped
      ansible.builtin.service:
        name: "{{ endlessh_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Endlessh systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ endlessh_identifier }}.service"
        state: absent

    - name: Ensure Endlessh path does not exist
      ansible.builtin.file:
        path: "{{ endlessh_base_path }}"
        state: absent
