---

- name: Check existence of endlessh systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ endlessh_identifier }}.service"
  register: endlessh_service_stat

- when: endlessh_service_stat.stat.exists | bool
  block:
    - name: Ensure endlessh service is stopped
      ansible.builtin.service:
        name: "{{ endlessh_identifier }}"
        state: stopped
        daemon_reload: true
    - name: Ensure endlessh service doesn't exist
      ansible.builtin.file:
        dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ endlessh_identifier }}.service"
        state: absent

    - name: Ensure endlessh base path is files deleted (make sure to delete node data)
      ansible.builtin.file:
        path: "{{ endlessh_base_path }}"
        state: absent
